name: Train Housing Price Prediction Model

on:
  push:
    branches:
      - main  # Exécuter uniquement lorsque du code est poussé sur la branche principale
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Version de Python que vous utilisez

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train and save model
        run: |
          python /home/runner/work/MLOps_Test/MLOps_Test/scripts/train_model.py

      - name: Upload model
        uses: actions/upload-artifact@v2
        with:
          name: model
          path: housing_price_prediction_model.pkl
    
      - name: Create Release
        uses: actions/create-release@latest
        with:
          tag_name: latest
          release_name: Release ${{ github.run_number }}
          body: |
            Changes in this Release:
            - Model trained and saved
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}